### ISSUE TITLE
/lib/modules/4.2.3-300.fc23.i686/build: No such file or directory.

### ISSUE THREAD

**Issue by zfyseu** [PeterHuewe/tpm-emulator#10]
Hello everyone!
I tried to install tpm emulator on Fedora 23.
When I do "make", it returns with the error:"/lib/modules/4.2.3-300.fc23.i686/build: No such file or directory."
How to solve the problem?
Thank you!

**Comment by zfyseu** [comment]
I have solve the problem above by running the following command:
"dnf install kernel-devel-$(uname -r)"
But when I do "make",it return with other errors:
`[ 96%] Generating linux/tpmd_dev.ko
Makefile:605: arch//Makefile: No such file or directory
make[4]: *** No rule to make target 'arch//Makefile'.  Stop.
Makefile:20: recipe for target 'all' failed
make[3]: *** [all] Error 2
tpmd_dev/CMakeFiles/tpmd_dev.dir/build.make:62: recipe for target 'tpmd_dev/linux/tpmd_dev.ko' failed
make[2]: *** [tpmd_dev/linux/tpmd_dev.ko] Error 2
CMakeFiles/Makefile2:383: recipe for target 'tpmd_dev/CMakeFiles/tpmd_dev.dir/all' failed
make[1]: *** [tpmd_dev/CMakeFiles/tpmd_dev.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by PeterHuewe** [comment]
are you sure you running the latest code?

**Comment by zfyseu** [comment]
Thank you, PeterHuewe!
There are no problems by using the lastest code.

**Comment by zfyseu** [comment]
But I still have to add "export ARCH=x86" to the Makefile.
