### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by aschmelter** [PeterHuewe/tpm-emulator#13]
Hi,

I try to install the tpm-emulator (v 0.7.4) on Ubuntu 16.04 32 bit, kernel 4.4.0 - 31.

After installing the dependencies the make process works fine. But when I try to "make install" I get the following error:

/Downloads/tpm-emulator-master/build$ sudo make install
[ 52%] Built target tpm
[ 73%] Built target mtm
[ 84%] Built target tpm_crypto
[ 87%] Built target tddl_static
[ 91%] Built target test_tddl
[ 94%] Built target tddl
[ 96%] Built target tpmd_dev
[100%] Built target tpmd
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/libtddl.so.1.2.0.7
-- Up-to-date: /usr/local/lib/libtddl.so.1.2
-- Up-to-date: /usr/local/lib/libtddl.so
-- Up-to-date: /usr/local/lib/libtddl.a
-- Up-to-date: /usr/local/include/tddl.h
**At main.c:222:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
  sign-file: certs/signing_key.pem: No such file or directory**
  -- Up-to-date: /usr/local/bin/tpmd
  andreas@andreas-VirtualBox:~/Downloads/tpm-emulator-master/build$ uname -a
  Linux andreas-VirtualBox 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:06:14 UTC 2016 i686 i686 i686 GNU/Linux

It looks that the signing_key.pem is not available. I tried to generate it with: ssh-keygen -t rsa, but nothing changes. Any idea whats wrong?

Kind regards an thanks,

Andreas

**Comment by PeterHuewe** [comment]
Hi Andreas,
the message is related to the signing process of the linux kernel, since module signing is enabled by default in ubuntu.

It's not that trivial to explain here, so unfortunately you have to google a bit on "ubuntu module signing" .
You can find a lot of similar questions if you search for "sign-file: certs/signing_key.pem: No such file or directory"

So this is unrelated to the tpm-emulator.

But if you find a working solution let us know.
Peter



Am 24. August 2016 05:29:34 GMT-07:00, schrieb Andreas <notifications@github.com>:
>Hi,
>
>I try to install the tpm-emulator (v 0.7.4) on Ubuntu 16.04 32 bit,
>kernel 4.4.0 - 31.
>
>After installing the dependencies the make process works fine. But when
>I try to "make install" I get the following error:
>
>/Downloads/tpm-emulator-master/build$ sudo make install
>[ 52%] Built target tpm
>[ 73%] Built target mtm
>[ 84%] Built target tpm_crypto
>[ 87%] Built target tddl_static
>[ 91%] Built target test_tddl
>[ 94%] Built target tddl
>[ 96%] Built target tpmd_dev
>[100%] Built target tpmd
>Install the project...
>-- Install configuration: ""
>-- Up-to-date: /usr/local/lib/libtddl.so.1.2.0.7
>-- Up-to-date: /usr/local/lib/libtddl.so.1.2
>-- Up-to-date: /usr/local/lib/libtddl.so
>-- Up-to-date: /usr/local/lib/libtddl.a
>-- Up-to-date: /usr/local/include/tddl.h
>**At main.c:222:
>- SSL error:02001002:system library:fopen:No such file or directory:
>bss_file.c:175
>- SSL error:2006D080:BIO routines:BIO_new_file:no such file:
>bss_file.c:178
>sign-file: certs/signing_key.pem: No such file or directory**
>-- Up-to-date: /usr/local/bin/tpmd
>andreas@andreas-VirtualBox:~/Downloads/tpm-emulator-master/build$ uname
>-a
>Linux andreas-VirtualBox 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13
>00:06:14 UTC 2016 i686 i686 i686 GNU/Linux
>
>It looks that the signing_key.pem is not available. I tried to generate
>it with: ssh-keygen -t rsa, but nothing changes. Any idea whats wrong?
>
>Kind regards an thanks,
>
>Andreas

-- 
Sent from my mobile

**Comment by aschmelter** [comment]
Thank you very much, the TPM is working.  I can see the device /dev/tpm0. If I can find something about the signing problem I will post it here.

But when I use tpmj, I get a file not found exception. 

**BasicTPMDriver: TPMIOException encountered. (edu.mit.csail.tpmj.TPMIOException: java.io.FileNotFoundException: /dev/tpm0 (Permission denied))
Waiting 2.0 s, then retrying ...**

It is independent from the user I used to run tpmj, tried it as root and normal user.  can you give me a hint whats wrong?

Kind regards,
Andreas

**Comment by PeterHuewe** [comment]
Hi,
is maybe tcsd running?
Only one application can access the /dev/tpm0 at a time.
Peter

Am 25. August 2016 09:24:43 GMT-04:00, schrieb Andreas <notifications@github.com>:
>Thank you very much, the TPM is working.  I can see the device
>/dev/tpm0. If I can find something about the signing problem I will
>post it here.
>
>But when I use tpmj, I get a file not found exception. 
>
>**BasicTPMDriver: TPMIOException encountered.
>(edu.mit.csail.tpmj.TPMIOException: java.io.FileNotFoundException:
>/dev/tpm0 (Permission denied))
>Waiting 2.0 s, then retrying ...**
>
>It is independent from the user I used to run tpmj, tried it as root
>and normal user.  can you give me a hint whats wrong?
>
>Kind regards,
>Andreas

-- 
Sent from my mobile

**Comment by PeterHuewe** [comment]
@aschmelter Any updates on your side?

**Comment by PeterHuewe** [comment]
@aschmelter Can we close this?
Peter

**Comment by aschmelter** [comment]
Dear Peter,

I’m really sorry that I  respond so late on your mail. Some topics were changed, and I had no time to work with the tpm emulator.

Yes, we can close the ticket.

Kind Regards,
Andreas

Von: Peter Huewe [mailto:notifications@github.com]
Gesendet: Mittwoch, 7. Dezember 2016 21:21
An: PeterHuewe/tpm-emulator <tpm-emulator@noreply.github.com>
Cc: Andreas Schmelter <andreas.schmelter@hs-owl.de>; Mention <mention@noreply.github.com>
Betreff: Re: [PeterHuewe/tpm-emulator] make install fails (#13)


@aschmelter<https://github.com/aschmelter> Can we close this?
Peter

**Comment by PeterHuewe** [comment]
If you need additional help, please let me know.

**Comment by lanzhuzhu** [comment]
how to solve the SSL problem? is there any solution? I met the same problem.

**Comment by PeterHuewe** [comment]
@lanzhuzhu 
the message is related to the signing process of the linux kernel, since module signing is enabled by default in ubuntu.

It's not that trivial to explain here, so unfortunately you have to google a bit on "ubuntu module signing" .
You can find a lot of similar questions if you search for "sign-file: certs/signing_key.pem: No such file or directory"

So this is unrelated to the tpm-emulator.
