### ISSUE TITLE
make fails on latest kernel

### ISSUE THREAD

**Issue by daytonpid** [PeterHuewe/tpm-emulator#14]
Seems that `sock_recvmsg` has changed in the latest kernel and has removed space for a argument, I tried just appending `tpm_response.size` instead of `tpm_response.size, 0` and the build succeeded. 

But this probably is not the proper fix as tcsd throws a `tpmd_dev.c:146: Error sock_recvmsg failed`. 

See the attached photo

![tpm-emulator-error](https://cloud.githubusercontent.com/assets/5340801/18047963/c772b5b4-6d9c-11e6-9f9b-1a569db9ab99.PNG)

**Comment by daytonpid** [comment]
Seems that it does not care about the len anymore and just flags, which are zero correct?

**Comment by PeterHuewe** [comment]
Hi
I will look into it.
Which kernel version are you using?
Peter

Am 29. August 2016 05:47:54 GMT-07:00, schrieb Dayton Pidhirney <notifications@github.com>:
>Seems that it does not care about the len anymore and just flags, which
>are zero correct?

-- 
Sent from my mobile

**Comment by daytonpid** [comment]
The latest stable: `4.7.2`. Thanks Peter.

**Comment by PeterHuewe** [comment]
Okay, thanks for the information.
I have 4.7.0 here that's why I'm a bit confused.

Will look into it though
Peter

Am 29. August 2016 08:10:32 GMT-07:00, schrieb Dayton Pidhirney <notifications@github.com>:
>The latest stable: `4.7.2`. Thanks Peter.

-- 
Sent from my mobile

**Comment by daytonpid** [comment]
https://github.com/torvalds/linux/commit/2da62906b1e298695e1bb725927041cd59942c98

**Comment by daytonpid** [comment]
Hi Peter, 

Any update on this? Or could you just let me know what needs to be changed so I can do it?

Thanks,

Dayton

**Comment by PeterHuewe** [comment]
Hi Dayton,

I just tried it and you are correct - it does not compile on latest kernels and it seems there is more to it than just removing the size parameter (since it was mainly removed since the value of the size parameter could be retrieved elsewhere).

I will have to look a bit deeper into it :/

**Comment by daytonpid** [comment]
Hi Peter, 

I would have tried to fix it myself and send a pull request, but unfortunately I'm not experienced enough with C.

Thank you for looking into this, let me know if you need a tester 😄

**Comment by PeterHuewe** [comment]
@aorimn: do you have time for a deeper look into that?

**Comment by PeterHuewe** [comment]
That one SHOULD be correct, but I couldn't get it to work though
[test.txt](https://github.com/PeterHuewe/tpm-emulator/files/512345/test.txt)

**Comment by Aorimn** [comment]
This patch with the latest Fedora 24 kernel at the moment (4.7.5-200.fc24.x86_64) is fixing the build.
I'm not sure if it works though, the [TPM/J](https://sourceforge.net/projects/tpmj/) class isn't working (independantly of tpm-emulator) and I have nothing to test it right now.

**Comment by daytonpid** [comment]
@Aorimn I will test shortly and let you know. Thanks

**Comment by PeterHuewe** [comment]
@Aorimn @daytonpid  Anyone could test this yet?
Thanks,
Peter

**Comment by Aorimn** [comment]
@PeterHuewe Sorry but I don't have time to test it.

**Comment by quitschbo** [comment]
@PeterHuewe I tested the patch #15 You were right about the message size. But not only the recvmsg were broken but also the sendmsg. There also the in_size was set to 1 in the iov init.

However, there exist kernel_sendmsg() and kernel_recvmsg() function which allow a simpler and more stable code. See my pull-request #21

**Comment by langbeck** [comment]
@PeterHuewe I tested patch #21 from @quitschbo and solved the build problem described by this issue.

**Comment by PeterHuewe** [comment]
Okay, I think we can close this one :) thanks @langbeck  @quitschbo
