### ISSUE TITLE
Build fails with gcc7

### ISSUE THREAD

**Issue by luigino** [PeterHuewe/tpm-emulator#26]
No problem with gcc6 instead. See attached log snippet.
[tpm_emulator_gcc7.txt](https://github.com/PeterHuewe/tpm-emulator/files/1100399/tpm_emulator_gcc7.txt)

**Comment by PeterHuewe** [comment]
that code looks unusual, yes.
To get it compiling you can of course -Wno-implicit-fallthrough but of course that does not solve the underlying rootcause - which is indeed a bug.

According to https://www.trustedcomputinggroup.org/wp-content/uploads/Revision_7.02-_29April2010-tcg-mobile-trusted-module-1.0.pdf it should return  "0x0000 0002 MTM_PERMANENT_DATA->verifiedPCRs" which in any case it does not - so it's a bug.


However I'm not sure if anybody ever used the MTM part and or will ever use it - so  I'm thinking of removing it altogether?

For your case, you can probably simply add 
´´´return TPM_FAIL;´´´
before the case 3.

**Comment by luigino** [comment]
We aren't there yet, see additional attachments.
[tpm_emulator-gcc7_2.txt](https://github.com/PeterHuewe/tpm-emulator/files/1101190/tpm_emulator-gcc7_2.txt)
[tpm_emulator-gcc7_3.txt](https://github.com/PeterHuewe/tpm-emulator/files/1101191/tpm_emulator-gcc7_3.txt)

**Comment by luigino** [comment]
Problem appears to have been fixed in 0.7.5.
