### ISSUE TITLE
TPM make install on Ubuntu 16.04 Server (VBClient)

### ISSUE THREAD

**Issue by tpmuser99** [PeterHuewe/tpm-emulator#31]
Have what appears to be an almost perfect build, minus the install errors
which I cant seem to find any reference or pointers to within the build 
itself.   Please see attached file.  Apologies for not including the text here as its
running in a VM and ... and .... 

![screen shot 2018-04-25 at 4 53 44 pm](https://user-images.githubusercontent.com/38739567/39278080-6d8ad13c-48ae-11e8-81f2-8e3851cf29c0.png)

**Comment by PeterHuewe** [comment]
This is because ubuntu 16.04 and up use signed kernel modules.
I would have to create a dkms package to be included in ubuntu.
Otherwise not much I can do - since the signing key is not available to me (as it would defeat the whole purpose of having signed modules).

**Comment by PeterHuewe** [comment]
Nothing I can do - won't fix.
So I close this for now.
