### ISSUE TITLE
/usr/include/tddl.h /usr/lib*/libtddl* conflict with trousers package

### ISSUE THREAD

**Issue by alonbl** [PeterHuewe/tpm-emulator#38]
Hello,

Both packages tpm-emulator and trousers cannot be installed on the same system because of file collision[1]. Can you please consider renaming the tddl to tpm-emulator-tddl or anything unique so that no collision will exist?

I can do this if you agree and specify desired name.

Thanks,
Alon

[1] https://bugs.gentoo.org/show_bug.cgi?id=537544

**Comment by PeterHuewe** [comment]
Hi,
thanks for noticing.
I would suggest appending tpm-emulator.
so
tddl-tpm-emulator.h 
and 
/usr/lib/libtddl-tpm-emulator.a

If you can prepare the patch, it would be appreciated.

**Comment by alonbl** [comment]
am on it

**Comment by alonbl** [comment]
ready at #40
