### ISSUE TITLE
TPM 2.0 Support?

### ISSUE THREAD

**Issue by coolrecep** [PeterHuewe/tpm-emulator#55]
Any way you can add TPM 2.0 support to the emulator?

**Comment by PeterHuewe** [comment]
hi,
tldr: no

tpm1.2 and 2.0 are way different. This project is here for historical reasons only.

in case you are looking for a simulator which can speak both, please use swtpm by stefan berger.
for a pure tpm2.0 simulator ibm and microsoft both provide one.
you can find more details at tpm2-software/tpm2-tss.
peter
