### ISSUE TITLE
tranpannt emulator on a board based on ARMv7

### ISSUE THREAD

**Issue by scanfsc** [PeterHuewe/tpm-emulator#7]
I want to tranpannt it on a board based on ARMv7. But i face some diffculty in compiling the module **tpmd_dev** . It require linux-headers ，but i can't install is on my board.
Did anyone ever meet problems like this before?

**Comment by PeterHuewe** [comment]
hmm, maybe try to compile it in a qemu based environment and then transfer?

**Comment by zfyseu** [comment]
Hello, scanfsc!
I also want to transplant it on Raspberry Pi which is based on ARMv7.
Have you done it successfully?

**Comment by PeterHuewe** [comment]
Hi I don't see why this should not work.
I think I tried it once.
Peter

Am 20. Juni 2016 00:44:26 GMT-07:00, schrieb zfyseu <notifications@github.com>:
>Hello, scanfsc!
>I also want to transplant it on Raspberry Pi which is based on ARMv7.
>Have you done it successfully?
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/PeterHuewe/tpm-emulator/issues/7#issuecomment-227071566

-- 
Sent from my mobile

**Comment by golubevmikhail** [comment]
Hi! I've cross compiled tmp dev to my beagle bone black. Works fine.
Mike.
20 июня 2016 г. 17:53 пользователь "Peter Huewe" <notifications@github.com>
написал:

**Comment by zfyseu** [comment]
Hello,everyone!
When I make tpm emulator on Fedora 23, it return with some errors:
`[ 96%] Generating linux/tpmd_dev.ko
/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c: In function ‘tpmd_handle_command’:
/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c:111:6: error: ‘struct msghdr’ has no member named ‘msg_iov’
   msg.msg_iov = &iov;
      ^
/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c:112:6: error: ‘struct msghdr’ has no member named ‘msg_iovlen’
   msg.msg_iovlen = 1;
      ^
/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c:113:9: error: too many arguments to function ‘sock_sendmsg’
   res = sock_sendmsg(tpmd_sock, &msg, in_size);
         ^
In file included from /home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c:25:0:
include/linux/net.h:213:5: note: declared here
 int sock_sendmsg(struct socket *sock, struct msghdr *msg);
     ^
/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c:125:6: error: ‘struct msghdr’ has no member named ‘msg_iov’
   msg.msg_iov = &iov;
      ^
/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c:126:6: error: ‘struct msghdr’ has no member named ‘msg_iovlen’
   msg.msg_iovlen = 1;
      ^
scripts/Makefile.build:264: recipe for target '/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.o' failed
make[5]: *** [/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.o] Error 1
Makefile:1390: recipe for target '_module_/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux' failed
make[4]: *** [_module_/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux] Error 2
Makefile:20: recipe for target 'all' failed
make[3]: *** [all] Error 2
tpmd_dev/CMakeFiles/tpmd_dev.dir/build.make:62: recipe for target 'tpmd_dev/linux/tpmd_dev.ko' failed
make[2]: *** [tpmd_dev/linux/tpmd_dev.ko] Error 2
CMakeFiles/Makefile2:383: recipe for target 'tpmd_dev/CMakeFiles/tpmd_dev.dir/all' failed
make[1]: *** [tpmd_dev/CMakeFiles/tpmd_dev.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`

Is there anyone konw how to solve the problem?

**Comment by PeterHuewe** [comment]
Hi,
which kernel version are you using?
Which version of the tpm emulator?

Thanks
Peter

Am 21. Juni 2016 18:44:36 GMT-07:00, schrieb zfyseu <notifications@github.com>:
>Hello,everyone!
>When I make tpm emulator on Fedora 23, it return with some errors:
>`[ 96%] Generating linux/tpmd_dev.ko
>/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c: In
>function ‘tpmd_handle_command’:
>/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c:111:6:
>error: ‘struct msghdr’ has no member named ‘msg_iov’
>   msg.msg_iov = &iov;
>      ^
>/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c:112:6:
>error: ‘struct msghdr’ has no member named ‘msg_iovlen’
>   msg.msg_iovlen = 1;
>      ^
>/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c:113:9:
>error: too many arguments to function ‘sock_sendmsg’
>   res = sock_sendmsg(tpmd_sock, &msg, in_size);
>         ^
>In file included from
>/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c:25:0:
>include/linux/net.h:213:5: note: declared here
> int sock_sendmsg(struct socket *sock, struct msghdr *msg);
>     ^
>/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c:125:6:
>error: ‘struct msghdr’ has no member named ‘msg_iov’
>   msg.msg_iov = &iov;
>      ^
>/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.c:126:6:
>error: ‘struct msghdr’ has no member named ‘msg_iovlen’
>   msg.msg_iovlen = 1;
>      ^
>scripts/Makefile.build:264: recipe for target
>'/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.o'
>failed
>make[5]: ***
>[/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux/tpmd_dev.o]
>Error 1
>Makefile:1390: recipe for target
>'_module_/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux' failed
>make[4]: ***
>[_module_/home/zfyseu/tpm-emulator-master/build/tpmd_dev/linux] Error 2
>Makefile:20: recipe for target 'all' failed
>make[3]: *** [all] Error 2
>tpmd_dev/CMakeFiles/tpmd_dev.dir/build.make:62: recipe for target
>'tpmd_dev/linux/tpmd_dev.ko' failed
>make[2]: *** [tpmd_dev/linux/tpmd_dev.ko] Error 2
>CMakeFiles/Makefile2:383: recipe for target
>'tpmd_dev/CMakeFiles/tpmd_dev.dir/all' failed
>make[1]: *** [tpmd_dev/CMakeFiles/tpmd_dev.dir/all] Error 2
>Makefile:149: recipe for target 'all' failed
>make: *** [all] Error 2
>`
>
>Is there anyone konw how to solve the problem?
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/PeterHuewe/tpm-emulator/issues/7#issuecomment-227621114

-- 
Sent from my mobile

**Comment by PeterHuewe** [comment]
The code should be there... this should not happen.
Please use latest master:

#if LINUX_VERSION_CODE < KERNEL_VERSION(3,19,0)
  msg.msg_iov = &iov;
  msg.msg_iovlen = 1;
#else
  iov_iter_init(&msg.msg_iter, WRITE, &iov, 1, 1);
#endif

**Comment by zfyseu** [comment]
Thank you!
The problem is solved.
And I want to build the code on ARM7 wich also use fedora 23.
How should I do ?

**Comment by PeterHuewe** [comment]
Easiest is to compile it directly on your arm board. Set ARCH accordingly
Peter

Am 22. Juni 2016 00:29:54 GMT-07:00, schrieb zfyseu <notifications@github.com>:
>Thank you!
>The problem is solved.
>And I want to build the code on ARM7 wich also use fedora 23.
>How should I do ?
>
>
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/PeterHuewe/tpm-emulator/issues/7#issuecomment-227664991

-- 
Sent from my mobile

**Comment by zfyseu** [comment]
Hello PeterHuewe!
When I build the code on ARM7, it return with the following error:
[ 96%] Generating linux/tpmd_dev.ko
make[4]: *** /lib/modules/4.2.5-400.50acac3.bcm2709.fc23.armv7hl/build: No such file or directory.  Stop.
Makefile:22: recipe for target 'all' failed
make[3]: *** [all] Error 2
tpmd_dev/CMakeFiles/tpmd_dev.dir/build.make:62: recipe for target 'tpmd_dev/linux/tpmd_dev.ko' failed
make[2]: *** [tpmd_dev/linux/tpmd_dev.ko] Error 2
CMakeFiles/Makefile2:383: recipe for target 'tpmd_dev/CMakeFiles/tpmd_dev.dir/all' failed
make[1]: *** [tpmd_dev/CMakeFiles/tpmd_dev.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

And I run the following command:
dnf install kernel-devel-$(uname -r)

However it return with the error:
No package kernel-devel-4.2.5-400.50acac3.bcm2709.fc23.armv7hl available.
Error: Unable to find a match.

Do you know how to solve the problem?

**Comment by zfyseu** [comment]
Hello PeterHuewe!
When I build the code on ARM7, it return with the following error:
[ 96%] Generating linux/tpmd_dev.ko
make[4]: *** /lib/modules/4.2.5-400.50acac3.bcm2709.fc23.armv7hl/build: No such file or directory.  Stop.
Makefile:22: recipe for target 'all' failed
make[3]: *** [all] Error 2
tpmd_dev/CMakeFiles/tpmd_dev.dir/build.make:62: recipe for target 'tpmd_dev/linux/tpmd_dev.ko' failed
make[2]: *** [tpmd_dev/linux/tpmd_dev.ko] Error 2
CMakeFiles/Makefile2:383: recipe for target 'tpmd_dev/CMakeFiles/tpmd_dev.dir/all' failed
make[1]: *** [tpmd_dev/CMakeFiles/tpmd_dev.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

And I run the following command:
dnf install kernel-devel-$(uname -r)

However it return with the error:
No package kernel-devel-4.2.5-400.50acac3.bcm2709.fc23.armv7hl available.
Error: Unable to find a match.

Do you know how to solve the problem?

**Comment by zfyseu** [comment]
Hello PeterHuewe!
When I build the code on ARM7, it return with the following error:
[ 96%] Generating linux/tpmd_dev.ko
make[4]: *** /lib/modules/4.2.5-400.50acac3.bcm2709.fc23.armv7hl/build: No such file or directory.  Stop.
Makefile:22: recipe for target 'all' failed
make[3]: *** [all] Error 2
tpmd_dev/CMakeFiles/tpmd_dev.dir/build.make:62: recipe for target 'tpmd_dev/linux/tpmd_dev.ko' failed
make[2]: *** [tpmd_dev/linux/tpmd_dev.ko] Error 2
CMakeFiles/Makefile2:383: recipe for target 'tpmd_dev/CMakeFiles/tpmd_dev.dir/all' failed
make[1]: *** [tpmd_dev/CMakeFiles/tpmd_dev.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

And I run the following command:
dnf install kernel-devel-$(uname -r)

However it return with the error:
No package kernel-devel-4.2.5-400.50acac3.bcm2709.fc23.armv7hl available.
Error: Unable to find a match.

Do you know how to solve the problem?

**Comment by zfyseu** [comment]
Hello PeterHuewe!
When I build the code on ARM7, it return with the following error:
[ 96%] Generating linux/tpmd_dev.ko
make[4]: *** /lib/modules/4.2.5-400.50acac3.bcm2709.fc23.armv7hl/build: No such file or directory.  Stop.
Makefile:22: recipe for target 'all' failed
make[3]: *** [all] Error 2
tpmd_dev/CMakeFiles/tpmd_dev.dir/build.make:62: recipe for target 'tpmd_dev/linux/tpmd_dev.ko' failed
make[2]: *** [tpmd_dev/linux/tpmd_dev.ko] Error 2
CMakeFiles/Makefile2:383: recipe for target 'tpmd_dev/CMakeFiles/tpmd_dev.dir/all' failed
make[1]: *** [tpmd_dev/CMakeFiles/tpmd_dev.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

And I run the following command:
dnf install kernel-devel-$(uname -r)

However it return with the error:
No package kernel-devel-4.2.5-400.50acac3.bcm2709.fc23.armv7hl available.
Error: Unable to find a match.

Do you know how to solve the problem?

**Comment by zfyseu** [comment]
Hello PeterHuewe!
When I build the code on ARM7, it return with the following error:
[ 96%] Generating linux/tpmd_dev.ko
make[4]: *** /lib/modules/4.2.5-400.50acac3.bcm2709.fc23.armv7hl/build: No such file or directory.  Stop.
Makefile:22: recipe for target 'all' failed
make[3]: *** [all] Error 2
tpmd_dev/CMakeFiles/tpmd_dev.dir/build.make:62: recipe for target 'tpmd_dev/linux/tpmd_dev.ko' failed
make[2]: *** [tpmd_dev/linux/tpmd_dev.ko] Error 2
CMakeFiles/Makefile2:383: recipe for target 'tpmd_dev/CMakeFiles/tpmd_dev.dir/all' failed
make[1]: *** [tpmd_dev/CMakeFiles/tpmd_dev.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

And I run the following command:
dnf install kernel-devel-$(uname -r)

However it return with the error:
No package kernel-devel-4.2.5-400.50acac3.bcm2709.fc23.armv7hl available.
Error: Unable to find a match.

Do you know how to solve the problem?

**Comment by zfyseu** [comment]
Hello PeterHuewe!
When I build the code on ARM7, it return with the following error:
[ 96%] Generating linux/tpmd_dev.ko
make[4]: *** /lib/modules/4.2.5-400.50acac3.bcm2709.fc23.armv7hl/build: No such file or directory.  Stop.
Makefile:22: recipe for target 'all' failed
make[3]: *** [all] Error 2
tpmd_dev/CMakeFiles/tpmd_dev.dir/build.make:62: recipe for target 'tpmd_dev/linux/tpmd_dev.ko' failed
make[2]: *** [tpmd_dev/linux/tpmd_dev.ko] Error 2
CMakeFiles/Makefile2:383: recipe for target 'tpmd_dev/CMakeFiles/tpmd_dev.dir/all' failed
make[1]: *** [tpmd_dev/CMakeFiles/tpmd_dev.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

And I run the following command:
dnf install kernel-devel-$(uname -r)

However it return with the error:
No package kernel-devel-4.2.5-400.50acac3.bcm2709.fc23.armv7hl available.
Error: Unable to find a match.

Do you know how to solve the problem?

**Comment by zfyseu** [comment]
Hello,everyone!
I have solved the problem.
first, do "dnf update" then do "dnf install kernel-devel" and then reboot.
And the problem will be solved.
