### ISSUE TITLE
TPM emulator won't create data

### ISSUE THREAD

**Issue by Melab** [PeterHuewe/tpm-emulator#8]
In the `/var/log/syslog` file, I keep on getting `tpm_startup.c:87: Error: restoring permanent data failed` and no `/var/lib/tpm/tpm_emulator-1_2_0_7` file gets created.

**Comment by PeterHuewe** [comment]
Hi,
the message appears when you try to issue a TPM_Startup(ST_STATE) instead of a TPM_Startup(Clear) - for ST_STATE you need a previous save state

**Comment by PeterHuewe** [comment]
can we close this ?

**Comment by Melab** [comment]
Yes.
